import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "Chat PDF",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Provider>
        <html lang="en">
          <body className="bg-gradient-to-r from-rose-100 to-teal-100">
            <Toaster />
            {children}
          </body>
        </html>
      </Provider>
    </ClerkProvider>
  );
}
